# Generated by Django 3.2.4 on 2021-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211110_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='displayName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
