# Generated by Django 3.2.4 on 2021-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211112_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
