# Generated by Django 3.2.4 on 2021-06-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
    ]
