# Generated by Django 3.2.4 on 2021-11-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211112_1841'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chatRooms',
            field=models.ManyToManyField(blank=True, null=True, to='chat.ChatRoom'),
        ),
    ]
